version: '3'

services:
        web:
                build: ./web 
                image: nginx 
                ports:
                        - "80:80"
                        - "143:143"
                volumes:
                        - ./web/public:/usr/share/nginx/html

